
/**
 * Hue API Error codes
 * @see https://developers.meethue.com/develop/hue-api/error-messages/
 */
export enum HueErrorCode {
  // Generic errors
  UNAUTHORIZED_USER = 1,
  INVALID_JSON = 2,
  RESOURCE_NOT_AVAILABLE = 3,
  INVALID_METHOD = 4,
  MISSING_BODY_PARAMETERS = 5,
  PARAMETER_NOT_AVAILABLE = 6,
  INVALID_VALUE_OR_PARAMETER = 7,
  PARAMETER_NOT_MODIFIABLE = 8,
  TOO_MANY_ITEMS_IN_LIST = 11,
  PORTAL_CONNECTION_REQUIRED = 12,
  INTERNAL_ERROR = 901,

  // Command-specific errors
  LINK_BUTTON_NOT_PRESSED = 101,
  DHCP_CANNOT_BE_ESTABLISHED = 110,
  INVALID_UPDATESTATE = 111,
  PARAMETER_IS_NOT_MODIFIABLE = 201,
  COMMISSIONABLE_LIGHT_LIST_FULL = 203,
  GROUP_TABLE_IS_FULL = 301,
  CANNOT_MODIFY_GROUP_OF_THIS_TYPE = 305,
  LIGHT_ALREADY_IN_ANOTHER_ROOM = 306,
  SCHENE_BUFFER_FULL = 402,
  SCENE_IS_LOCKED = 403,
  GROUP_IS_EMPTY = 404,
  NOT_ALLOWED_CREATION_OF_SENSOR_TYPE = 501,
  SENSOR_LIST_FULL = 502,
  COMMISSIONABLE_SENSOR_LIST_FULL = 503,
  RULE_ENGINE_FULL = 601,
  CONDITION_ERROR = 607,
  ACTION_ERROR = 608,
  UNABLE_TO_ACTIVATE = 609,
  SCHEDULE_LIST_FULL = 701,
  INVALID_TIME_ZONE = 702,
  SCHEDULE_ONLY_TIME_OR_LOCALTIME = 703,
  CANNOT_CREATE_SCHEDULE = 704,
  SCHEDULE_IS_IN_PAST = 705,
  SCHEDULE_COMMAND_ERROR = 706,
  BACKUP_SOURCE_MODEL_INVALID = 801,
  BACKUP_SOURCE_FACTORY_NEW = 802,
  BACKUP_STATE_INVALID = 803,
}
